---
- hosts: "{{ host }}"
  become: true
  gather_facts: yes
  tasks:
    - name: deploy chart on cluster
      k8s:
        definition: "{{ lookup('template', 'values.yaml') }}"
        force: yes
        state: present
