- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: deploy chart
      k8s:
        definition: '{{ item }}'
          kubeconfig: '~/.kube/config'
          state: present
        definition: "{{ lookup('template', 'helm_chart.yaml') }}"
        force: yes
        state: present
