- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: deploy chart
      config:
        definition: '{{ item }}'
        kubeconfig: '~/.kube/config'
        state: present
      k8s:
        definition: "{{ lookup('template', 'helm_chart.yaml') }}"
        force: yes
        state: present
